<?php

/*
CLASS-BLOCKS.PHP WILL OVERRIDE THE CHOICES ARRAYS
*/

if ( function_exists( 'lazyblocks' ) ) :

    lazyblocks()->add_block( array(
        'id' => 866,
        'title' => 'Airconnex Navigation',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76 0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71 0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71 0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76 0 5-2.24 5-5s-2.24-5-5-5z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/airconnex-navigation',
        'description' => '',
        'category' => 'text',
        'category_label' => 'text',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_032a71424a' => array(
                'type' => 'select',
                'name' => 'normal_pages',
                'default' => '',
                'label' => 'Top Level Page',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => 'Airconnex : Wordpress Plugin for Airtable',
                        'value' => 2,
                    ),
                    array(
                        'label' => 'Categories',
                        'value' => 917,
                    ),
                    array(
                        'label' => 'Contact Us',
                        'value' => 192,
                    ),
                    array(
                        'label' => 'Create an Account',
                        'value' => 122,
                    ),
                    array(
                        'label' => 'Instructions',
                        'value' => 148,
                    ),
                    array(
                        'label' => 'My Websites',
                        'value' => 124,
                    ),
                    array(
                        'label' => 'People Portal',
                        'value' => 915,
                    ),
                    array(
                        'label' => 'Privacy Policy',
                        'value' => 3,
                    ),
                    array(
                        'label' => 'Thankyou.',
                        'value' => 134,
                    ),
                    array(
                        'label' => 'Welcome',
                        'value' => 1,
                    ),
                ),
                'allow_null' => 'true',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_79ea8c41b3' => array(
                'type' => 'select',
                'name' => 'linked_field',
                'default' => '',
                'label' => 'Parent Page',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                ),
                'allow_null' => 'true',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'html',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'always',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 214,
        'title' => 'Airconnex Form',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M21 3.01H3c-1.1 0-2 .9-2 2V9h2V4.99h18v14.03H3V15H1v4.01c0 1.1.9 1.98 2 1.98h18c1.1 0 2-.88 2-1.98v-14c0-1.11-.9-2-2-2zM11 16l4-4-4-4v3H1v2h10v3z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/airconnex-form',
        'description' => '',
        'category' => 'text',
        'category_label' => 'text',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_cb0957451b' => array(
                'type' => 'select',
                'name' => 'form_connection',
                'default' => '',
                'label' => 'Data Source',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => '(Add) Je > Orders',
                        'value' => 'A_2882',
                    ),
                    array(
                        'label' => '(Add) Pr > People',
                        'value' => 'A_880',
                    ),
                    array(
                        'label' => '(Add) Je > Products',
                        'value' => 'A_489',
                    ),
                    array(
                        'label' => '(Add) Je > Categories',
                        'value' => 'A_457',
                    ),
                    array(
                        'label' => '(Add) Pr > Resources',
                        'value' => 'A_217',
                    ),
                ),
                'allow_null' => 'true',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_bec8cb42c5' => array(
                'type' => 'classic_editor',
                'name' => 'contents',
                'default' => 'Add your form contents here...',
                'label' => 'Form Contents',
                'help' => 'You can use the placeholders in the airconnex menu to display field inputs.',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'true',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
                'multiline' => 'true',
            ),
        ),
        'code' => array(
            'output_method' => 'html',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'always',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 200,
        'title' => 'Airconnex Loop',
        'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
    </svg>
    ',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/airconnex-loop',
        'description' => '',
        'category' => 'text',
        'category_label' => 'text',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_b33a8b4683' => array(
                'type' => 'select',
                'name' => 'connection',
                'default' => '',
                'label' => 'Data Source',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => '(Data) Je > Orders',
                        'value' => 2882,
                    ),
                    array(
                        'label' => '(Data) Pr > People',
                        'value' => 880,
                    ),
                    array(
                        'label' => '(Data) Je > Products',
                        'value' => 489,
                    ),
                    array(
                        'label' => '(Data) Je > Categories',
                        'value' => 457,
                    ),
                    array(
                        'label' => '(Data) Pr > Resources',
                        'value' => 217,
                    ),
                    array(
                        'label' => '(Pages) Products',
                        'value' => 'P_671_489',
                    ),
                    array(
                        'label' => '(Pages) Categories',
                        'value' => 'P_473_457',
                    ),
                    array(
                        'label' => '(Pages) Resources',
                        'value' => 'P_318_217',
                    ),
                ),
                'allow_null' => 'true',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_16c93649f6' => array(
                'type' => 'select',
                'name' => 'dynamic_filter',
                'default' => '',
                'label' => 'Dynamic Filter',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                ),
                'allow_null' => 'true',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_bb2b2d4858' => array(
                'type' => 'repeater',
                'name' => 'filter_buttons',
                'default' => '',
                'label' => 'Filter Buttons',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'true',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => 'Button {{#}}',
                'rows_add_button_label' => '+ Add Filter',
                'rows_collapsible' => 'false',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_999b76445c' => array(
                'type' => 'select',
                'name' => 'layout',
                'default' => 'GRTO',
                'label' => 'Layout',
                'help' => 'Choose a layout for your loop.',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => 'acx_loop_layout',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => 'Grid Top',
                        'value' => 'GRTO',
                    ),
                    array(
                        'label' => 'Grid Left',
                        'value' => 'GRLE',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_4488024ddf' => array(
                'type' => 'select',
                'name' => 'columns',
                'default' => '3',
                'label' => 'Columns',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => '1',
                        'value' => '1',
                    ),
                    array(
                        'label' => '2',
                        'value' => '2',
                    ),
                    array(
                        'label' => '3',
                        'value' => '3',
                    ),
                    array(
                        'label' => '4',
                        'value' => '4',
                    ),
                    array(
                        'label' => '6',
                        'value' => '6',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
                'min' => '1',
                'max' => '12',
            ),
            'control_f6ea3845dc' => array(
                'type' => 'range',
                'name' => 'height',
                'default' => '250',
                'label' => 'Height',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'min' => '50',
                'max' => '500',
                'step' => '5',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6d08d64421' => array(
                'type' => 'text',
                'name' => 'heading',
                'default' => '',
                'label' => 'Heading',
                'help' => 'Add a custom heading value.',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_464b2e49ef' => array(
                'type' => 'classic_editor',
                'name' => 'paragraph',
                'default' => '',
                'label' => 'Paragraph',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
                'multiline' => 'true',
            ),
            'control_1e28f3413e' => array(
                'type' => 'select',
                'name' => 'alignment',
                'default' => '',
                'label' => 'Text Alignment',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => 'Left',
                        'value' => 'left',
                    ),
                    array(
                        'label' => 'Center',
                        'value' => 'center',
                    ),
                    array(
                        'label' => 'Right',
                        'value' => 'right',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_82488c4198' => array(
                'type' => 'range',
                'name' => 'lines',
                'default' => '',
                'label' => 'Excerpt Lines',
                'help' => 'Choose zero for unlimited.',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'min' => '0',
                'max' => '20',
                'step' => '1',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_2228724f7e' => array(
                'type' => 'text',
                'name' => 'image',
                'default' => '',
                'label' => 'Image URL',
                'help' => 'Add a custom image.',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_e0db8c4544' => array(
                'type' => 'select',
                'name' => 'imagecols',
                'default' => '4',
                'label' => 'Image Area',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => '1/6',
                        'value' => '2',
                    ),
                    array(
                        'label' => '1/4',
                        'value' => '3',
                    ),
                    array(
                        'label' => '1/3',
                        'value' => '4',
                    ),
                    array(
                        'label' => '1/2',
                        'value' => '6',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_ee2aca4f70' => array(
                'type' => 'toggle',
                'name' => 'imagesquare',
                'default' => '250',
                'label' => 'Image Square',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'checked' => 'false',
                'alongside_text' => '',
                'placeholder' => '',
                'characters_limit' => '',
                'min' => '5',
                'max' => '500',
                'step' => '5',
                'choices' => array(
                    array(
                        'label' => '',
                        'value' => 'square',
                    ),
                ),
            ),
            'control_beb8324ad9' => array(
                'type' => 'range',
                'name' => 'imageradius',
                'default' => '0',
                'label' => 'Image Border Radius',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'min' => '0',
                'max' => '50',
                'step' => '1',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6838fd4cf4' => array(
                'type' => 'radio',
                'name' => 'imagefit',
                'default' => 'cover',
                'label' => 'Image Fit',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => 'Cover',
                        'value' => 'cover',
                    ),
                    array(
                        'label' => 'Contain',
                        'value' => 'contain',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_7d0ba145d2' => array(
                'type' => 'text',
                'name' => 'link_url',
                'default' => '',
                'label' => 'Button URL',
                'help' => 'Add a custom link.',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_4e9b9d4070' => array(
                'type' => 'text',
                'name' => 'button_text',
                'default' => '',
                'label' => 'Button Text',
                'help' => 'Leave this empty to avoid linking.',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_586b6b4250' => array(
                'type' => 'select',
                'name' => 'buttonstyle',
                'default' => 'text',
                'label' => 'Button Style',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => 'Text',
                        'value' => 'text',
                    ),
                    array(
                        'label' => 'Solid',
                        'value' => 'solid',
                    ),
                    array(
                        'label' => 'Outline',
                        'value' => 'outline',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fb9a81426d' => array(
                'type' => 'color',
                'name' => 'buttoncolor',
                'default' => '',
                'label' => 'Button Color',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'alpha' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_3d2a754f6c' => array(
                'type' => 'text',
                'name' => 'value',
                'default' => '',
                'label' => 'Value',
                'help' => '',
                'child_of' => 'control_bb2b2d4858',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'php',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'always',
            'single_output' => true,
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 199,
        'title' => 'Airconnex Image',
        'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
    </svg>
    ',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/airconnex-image',
        'description' => '',
        'category' => 'media',
        'category_label' => 'media',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_6ae98c40ec' => array(
                'type' => 'text',
                'name' => 'url',
                'default' => '',
                'label' => 'Image URL',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6f898d4f98' => array(
                'type' => 'range',
                'name' => 'width',
                'default' => '400',
                'label' => 'Max Width',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'min' => '20',
                'max' => '1000',
                'step' => '10',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fd79024cd7' => array(
                'type' => 'range',
                'name' => 'height',
                'default' => '400',
                'label' => 'Max Height',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'min' => '20',
                'max' => '1000',
                'step' => '10',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_af382841e0' => array(
                'type' => 'select',
                'name' => 'shape',
                'default' => '',
                'label' => 'Shape',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'choices' => array(
                    array(
                        'label' => 'Original',
                        'value' => 'or',
                    ),
                    array(
                        'label' => 'Rectangle',
                        'value' => 're',
                    ),
                    array(
                        'label' => 'Square',
                        'value' => 'sq',
                    ),
                    array(
                        'label' => 'Circle',
                        'value' => 'ci',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'php',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'always',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 198,
        'title' => 'Airconnex Text',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M14 17H4v2h10v-2zm6-8H4v2h16V9zM4 15h16v-2H4v2zM4 5v2h16V5H4z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/airconnex-text',
        'description' => '',
        'category' => 'text',
        'category_label' => 'text',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_a9cb994752' => array(
                'type' => 'classic_editor',
                'name' => 'text',
                'default' => '',
                'label' => 'text',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'true',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'php',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'always',
            'single_output' => true,
        ),
        'condition' => array(
        ),
    ) );
    
endif;
